- name: Upgrade Proxmox Node with Semaphore
  hosts: all  # Replace with your node group
  become: true
  gather_facts: yes

  tasks:
    - name: Gather Facts (including Proxmox Version)
      setup:

    - name: Debug ansible_kernel
      debug:
        msg: "ansible_kernel: {{ ansible_kernel }}"

    - name: Debug Proxmox Version (if available)
      debug:
        msg: "Proxmox Version: {{ ansible_facts.get('proxmox_version', 'Not available') }}"

    - name: Check for Kernel Update
      debug:
        msg: "Kernel needs reboot: {{ (ansible_kernel | regex_replace('^([0-9.]+).*')) != ansible_facts['proxmox_version'] OR ansible_facts.get('proxmox_version', 'Not available') }}"

    - name: Acquire Semaphore Lock
      shell: touch /tmp/proxmox_upgrade_semaphore.lock
      args:
        creates: /tmp/proxmox_upgrade_semaphore.lock
      ignore_errors: yes

    # Your other tasks go here...

    - name: Release Semaphore Lock
      shell: rm -f /tmp/proxmox_upgrade_semaphore.lock
      ignore_errors: yes

  vars:
    migrate_vms: "{{ 'true' }}"  # Set to false to skip VM migration
    # Removed kernel_needs_reboot as it's calculated in the Check for Kernel Update task
