- name: Upgrade Proxmox Node with Semaphore
  hosts: all  # Replace with your node group
  become: true
  gather_facts: yes

  tasks:
    - name: Gather Facts (including Proxmox Version)
      setup:

    - name: Debug ansible_kernel
      debug:
        msg: "ansible_kernel: {{ ansible_kernel }}"

    - name: Debug Proxmox Version (assuming it's a fact)
      debug:
        msg: >
         {% if ansible_facts.proxmox_version is defined %}
         Proxmox Version: {{ ansible_facts.proxmox_version }}
          {% else %}
          Proxmox Version: Not available
          {% endif %}

    - name: Check for Kernel Update
      debug:
        msg: "Kernel needs reboot: {{ (ansible_kernel | regex_replace('^([0-9.]+).*')) != ansible_facts['proxmox_version'] }}"

    - name: Acquire Semaphore Lock
      shell: touch /tmp/proxmox_upgrade_semaphore.lock
      args:
        creates: /tmp/proxmox_upgrade_semaphore.lock
      ignore_errors: yes

    # Your other tasks go here...

    - name: Release Semaphore Lock
      shell: rm -f /tmp/proxmox_upgrade_semaphore.lock
      ignore_errors: yes

  vars:
    migrate_vms: "{{ 'true' }}"  # Set to false to skip VM migration
    # Removed kernel_needs_reboot as it's calculated in the Check for Kernel Update task
