---
- name: Upgrade Proxmox Node with Semaphore
  hosts: all  # Replace with your node group
  become: true

  tasks:
    - name: Debug ansible_kernel
      debug:
        msg: "ansible_kernel: {{ ansible_kernel }}"

    - name: Debug proxmox_version.kernel
      debug:
        msg: "proxmox_version.kernel: {{ proxmox_version.kernel }}"

    - name: Check for Kernel Update
      debug:
        msg: "Kernel needs reboot: {{ ansible_kernel | regex_replace('^([0-9.]+).*') != proxmox_version.kernel }}"

    - name: Acquire Semaphore Lock
      shell: touch /tmp/proxmox_upgrade_semaphore.lock
      args:
        creates: /tmp/proxmox_upgrade_semaphore.lock
      ignore_errors: yes

    # Your other tasks go here...

    - name: Release Semaphore Lock
      shell: rm -f /tmp/proxmox_upgrade_semaphore.lock
      ignore_errors: yes

  vars:
    migrate_vms: "{{ 'true' }}"  # Set to false to skip VM migration
    kernel_needs_reboot: "{{ ansible_kernel | regex_replace('^([0-9.]+).*') != proxmox_version.kernel }}"  # Check for kernel version change
